"""Core immutable domain dataclasses and typed contracts."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone

from .enums import AssetClass, ExecutionMode, OrderSide, OrderStatus, OrderType


@dataclass(frozen=True)
class Instrument:
    """Financial instrument definition."""
    symbol: str
    asset_class: AssetClass
    currency: str = "USD"
    multiplier: float = 1.0
    tick_size: float = 0.01

    def __post_init__(self) -> None:
        if not self.symbol or not isinstance(self.symbol, str):
            raise ValueError(f"Invalid instrument symbol: {self.symbol!r}")
        if self.multiplier <= 0:
            raise ValueError(f"Multiplier must be positive, got {self.multiplier}")
        if self.tick_size <= 0:
            raise ValueError(f"Tick size must be positive, got {self.tick_size}")


@dataclass(frozen=True)
class Signal:
    """Conviction signal emitted by a strategy engine for an instrument."""
    timestamp: datetime
    strategy_id: str
    symbol: str
    score: float
    metadata: dict = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not self.strategy_id:
            raise ValueError("strategy_id cannot be empty")
        if not self.symbol:
            raise ValueError("symbol cannot be empty")


@dataclass(frozen=True)
class TargetPortfolio:
    """Desired portfolio allocation generated by a strategy engine."""
    timestamp: datetime
    strategy_id: str
    target_weights: dict[str, float]
    rebalance_horizon: int
    metadata: dict = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not self.strategy_id:
            raise ValueError("strategy_id cannot be empty")
        if self.rebalance_horizon <= 0:
            raise ValueError(f"rebalance_horizon must be positive, got {self.rebalance_horizon}")
        for sym, w in self.target_weights.items():
            if not isinstance(w, (int, float)):
                raise TypeError(f"Weight for {sym} must be numeric, got {type(w)}")
            if abs(w) > 1.0:
                raise ValueError(f"Single asset target weight for {sym} cannot exceed +/-1.0, got {w}")


@dataclass(frozen=True)
class RiskDecision:
    """Pre-trade risk engine decision regarding a target portfolio."""
    timestamp: datetime
    approved: bool
    adjusted_weights: dict[str, float] = field(default_factory=dict)
    violations: list[str] = field(default_factory=list)
    decision_id: str = ""
    portfolio_id: str = ""
    strategy_id: str = ""
    metrics: dict[str, float] = field(default_factory=dict)
    metadata: dict = field(default_factory=dict)


@dataclass(frozen=True)
class Order:
    """Order generated by Order Management System."""
    order_id: str
    run_id: str
    strategy_id: str
    symbol: str
    side: OrderSide
    order_type: OrderType
    quantity: float
    limit_price: float | None = None
    client_order_id: str | None = None
    execution_mode: ExecutionMode = ExecutionMode.RESEARCH
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    status: OrderStatus = OrderStatus.CREATED

    def __post_init__(self) -> None:
        if not self.order_id:
            raise ValueError("order_id cannot be empty")
        if not self.symbol:
            raise ValueError("symbol cannot be empty")
        if self.quantity <= 0:
            raise ValueError(f"Order quantity must be positive, got {self.quantity}")


@dataclass(frozen=True)
class OrderBatch:
    """Batch of orders generated from a specific target portfolio."""
    batch_id: str
    target_portfolio_id: str
    strategy_id: str
    orders: list[Order] = field(default_factory=list)
    execution_mode: ExecutionMode = ExecutionMode.RESEARCH
    generated_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: dict = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not self.batch_id:
            raise ValueError("batch_id cannot be empty")
        if not self.target_portfolio_id:
            raise ValueError("target_portfolio_id cannot be empty")
        if not self.strategy_id:
            raise ValueError("strategy_id cannot be empty")


@dataclass(frozen=True)
class Fill:
    """Execution fill returned by a broker adapter."""
    fill_id: str
    order_id: str
    symbol: str
    side: OrderSide
    quantity: float
    fill_price: float
    commission: float
    timestamp: datetime

    def __post_init__(self) -> None:
        if not self.fill_id:
            raise ValueError("fill_id cannot be empty")
        if not self.order_id:
            raise ValueError("order_id cannot be empty")
        if self.quantity <= 0:
            raise ValueError(f"Fill quantity must be positive, got {self.quantity}")
        if self.fill_price <= 0:
            raise ValueError(f"Fill price must be positive, got {self.fill_price}")
        if self.commission < 0:
            raise ValueError(f"Commission cannot be negative, got {self.commission}")


@dataclass(frozen=True)
class Holding:
    """Current physical asset holding."""
    symbol: str
    shares: float
    cost_basis: float
    current_price: float
    market_value: float

    def __post_init__(self) -> None:
        if not self.symbol:
            raise ValueError("symbol cannot be empty")


@dataclass(frozen=True)
class PortfolioState:
    """Point-in-time portfolio mark-to-market snapshot."""
    timestamp: datetime
    cash: float
    holdings: dict[str, Holding]
    nav: float
    realized_weights: dict[str, float]

    def __post_init__(self) -> None:
        calculated_mv = sum(h.market_value for h in self.holdings.values())
        expected_nav = self.cash + calculated_mv
        # Allow small floating point epsilon in verification
        if abs(self.nav - expected_nav) > 1e-4 * max(1.0, abs(self.nav)):
            raise ValueError(
                f"NAV mismatch: nav={self.nav:.4f} but cash({self.cash:.4f}) + "
                f"holdings_mv({calculated_mv:.4f}) = {expected_nav:.4f}"
            )
